server:
  port: 19040

spring:
  application:
    name: reservation-service


  datasource:
    url: ${RESERVATION_DB_URL}
    username: ${RESERVATION_DB_USER}
    password: ${RESERVATION_DB_PW}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      show-sql: true
      format-sql: true
      use_sql_comments: true

#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:19090/eureka/

