name: Issue and PR Labeler
on:
  issues:
    types: [opened, edited]
  pull_request_target:
    types: [opened, synchronize]

jobs:
  label:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      issues: write

    steps:
      - name: Label Issues Based on Title or Body
        if: ${{ github.event_name == 'issues' }}
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: |
            âš™ Setting
            âœ¨ Feature
            ğŸŒ Deploy
            ğŸ¨ Html&css
            ğŸ BugFix
            ğŸ’» CrossBrowsing
            ğŸ“ƒ Docs
            ğŸ“¬ API
            ğŸ”¨ Refactor
            ğŸ™‹â€â™‚ï¸ Question
            ğŸ¥° Accessibility
            âœ… Test

      - name: Label Pull Requests Based on Changed Files
        if: ${{ github.event_name == 'pull_request_target' }}
        uses: actions/labeler@v4
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
