name: Issue and PR Labeler
on:
  issues:
    types: [opened, edited]
  pull_request:
    types: [opened, synchronize, edited]

jobs:
  label:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      issues: write

    steps:
      - name: Label Issues and PRs Based on Title or Body
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: |
            âš™ Setting:
              - setting
            âœ¨ Feature:
              - feature
            ğŸŒ Deploy:
              - deploy
            ğŸ¨ Html&css:
              - html
              - css
            ğŸ BugFix:
              - bugfix
            ğŸ“ƒ Docs:
              - docs
            ğŸ”¨ Refactor:
              - refactor
            âœ… Test:
              - test
            ğŸ™‹â€â™‚ï¸ Question:
              - question
            ğŸ¥° Accessibility:
              - accessibility
            ğŸ’» CrossBrowsing:
              - crossbrowsing
            ğŸ“¬ API:
              - api
