name: Simple Labeler
on:
  issues:
    types: [opened, edited]
  pull_request:
    types: [opened, ready_for_review]

jobs:
  simple-labeler:
    runs-on: ubuntu-latest
    steps:
      - name: Labeler
        uses: actions-ecosystem/action-add-labels-by-query@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: |
            âš™ Setting:
              - setting
            âœ¨ Feature:
              - feature
            ğŸŒ Deploy:
              - deploy
            ğŸ¨ Html&css:
              - html
              - css
            ğŸ BugFix:
              - bugfix
            ğŸ“ƒ Docs:
              - docs
            ğŸ”¨ Refactor:
              - refactor
            âœ… Test:
              - test
            ğŸ™‹â€â™‚ï¸ Question:
              - question
            ğŸ¥° Accessibility:
              - accessibility
            ğŸ’» CrossBrowsing:
              - crossbrowsing
            ğŸ“¬ API:
              - api
