name: Simple Labeler
on:
  issues:
    types: [opened, edited]
  pull_request:
    types: [opened, ready_for_review]

jobs:
  simple-labeler:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Labels for Issues
        if: ${{ github.event_name == 'issues' }}
        uses: actions/labeler@v4
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          configuration-path: .github/labeler.yml

      - name: Setup Labels for Pull Requests
        if: ${{ github.event_name == 'pull_request' }}
        uses: actions/labeler@v4
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          configuration-path: .github/labeler.yml

      - name: Debug Logging
        run: |
          echo "Event Name: ${{ github.event_name }}"
          echo "Event Payload: ${{ toJSON(github.event) }}"
